# ~/.config/starship.toml
#
# build with Nerd font: Hack Nerd or FiraCode Nerd
#

# Use custom format
format = '''
[┌──────≻](bold blue) $username [on](bold white) $hostname : $directory $git_branch $git_status $combined [≺](bold blue)$fill[≻](bold blue) $time
[└──≻](bold blue) $character'''

command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

[username]
show_always = true
style_user = "yellow bold"
style_root = "red bold"
format = "[$user]($style)"

[hostname]
style = "bold yellow"
ssh_only = false
format = "[$hostname]($style)"
trim_at = ".companyname.com"
disabled = false

[localip]
ssh_only = false
style = "bg:#626774"
format = '[ $localipv4 ]($style)'
disabled = false

[directory]
style = "bold yellow"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bold white"
format = '[$symbol $branch]($style)'

[git_status]
style = "bold white"
format = '[$all_status $ahead_behind]($style)'

[fill]
symbol = "─"
style = "bold blue"

[cmd_duration]
style = "fg:#4e5463 bg:#c4c6cb"
format = "[ $duration ]($style)"

[jobs]
symbol = ""
number_threshold = 1
style = "fg:#3b4252 bg:#d7d9dc"
format = "[ $symbol ]($style)"

[time]
disabled = false
time_format = "%T"
style = "bold white"
format = '[$time]($style) '

[shell]
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[character]
success_symbol = "[](bold white)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[❮](green)"
